Hotfix/cyclicdependencyfix
the-sortinghat/pattern-detector pull request #11
Opened 2024-06-27 22:55 UTC by marcelo-vidu

2024-06-28 20:08 UTC, jooaodanieel requested changes

2024-06-28 20:08 UTC, jooaodanieel commented on app-analyses/src/main/kotlin/com/usvision/analyses/detector/CyclicDependency.kt
> +        visited.remove(startingFrom)
Essa linha me chamou muito a atenção, porque ela quebra o algoritmo de visitação em casos mais complexos. Rodei na minha máquina sem ela, e os testes continuaram passando. Acho melhor remover.

2024-06-29 00:18 UTC, marcelo-vidu commented on app-analyses/src/main/kotlin/com/usvision/analyses/detector/CyclicDependency.kt
> +        visited.remove(startingFrom)
Feito

2024-06-29 07:20 UTC, jooaodanieel approved these changes

2024-06-29 13:16 UTC, merged