Feature/similarservice implementation
the-sortinghat/pattern-detector pull request #12
Opened 2024-07-31 01:42 UTC by marcelo-vidu

Add similarservice smell detection.

2024-08-09 06:59 UTC, jooaodanieel requested changes
Antes de avançar para a revisão do detector `SimilarService`, eu resolvi dar feedback sobre o analyzer `CoincidenceOfMicroservice`, porque acho que tem um problema conceitual na sua implementação que afeta o detector por consequência. Primeiro, trata o que tem comentado, seja no código direto ou nesse bloco abaixo; depois vemos o detector em si.

Pensando no valor para o usuário da nossa ferramenta, nesse caso da detecção de serviços semelhantes, eu acredito que os dados mais importantes sejam justamente quais os outros serviços semelhantes, ao invés de qual o tipo de coincidência. Isso reflete diretamente nos dados coletados com o analyzer, i.e., só podemos informar na detecção a lista de coincidências de um serviço se tivermos coletado esse dado na análise -- o tipo de coincidência é algo que fica implícito.

Além disso, eu sinto que essa relação de coincidência não é transitiva. O que quero dizer? Se A coincide com B, e B coincide com C, não necessariamente A coincide com C. Vou dar um exemplo mais concreto, imagine o seguinte cenário (que seria bom entrar como teste no analyzer)

Service A
- expõe op. "POST /users"
- usa DB "users"
- publica no channel "users"

Service B
- expõe op. "POST /users"
- expõe op. "PUT /users/:uid"
- usa DB "users"
- publica no channel "users"

Service C
- expõe op. "PUT /users/:uid"
- usa DB "users"
- publica no channel "users"


Nesse exemplo, eu espero que o analyzer devolva algo como
```
{
   A: [B],
   B: [A, C],
   C: [B]
}
```
ou seja, existem coincidências entre A e B, e entre B e C.

2024-08-09 06:59 UTC, jooaodanieel commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/AsyncDependenciesOfMicroservice.kt
> +            }
Qual foi a necessidade de alterar esse código?
A nova versão faz praticamente o mesmo que a anterior, de uma forma mais verbosa -- e sem a verificação de vazio explícita. Inclusive, o novo teste adicionado no `test/.../AsyncDependenciesOfMicroserviceTest` passa com a versão anterior.

Nesse caso, sugiro reverter essa função para a versão anterior.

2024-08-09 06:59 UTC, jooaodanieel commented on app-analyses/src/test/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservicesTest.kt
> +        assertTrue { results[cons2]!!.any { it.second == "sync" } }
Eu vejo mais valor em saber quais os outros serviços que está coincidindo do que o "tipo" da coincidência.

2024-08-09 06:59 UTC, jooaodanieel commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservices.kt
> +    private val msCoincidences: MutableMap<Visitable, MutableList<Pair<Relationship, String>>> = mutableMapOf()
Idem em relação ao comentário em `test/.../ConcidenceOfMicroserviceTest` sobre "tipo" vs. lista de serviços.

2024-08-09 06:59 UTC, jooaodanieel commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservices.kt
> +    }
Muito cuidado com métodos assim. Repara que para todos os casos, o algoritmo é rigorosamente o mesmo, a não ser pela string do tipo de coincidência.
Aqui não vale re-entrar na discussão sobre o valor do "tipo", mas sobre a implementação sim: a repetição poderia ser substituída por um método auxiliar que implementa o algoritmo e recebe como parâmetro as listas necessárias e a string do tipo.

2024-09-29 11:23 UTC, marcelo-vidu commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/AsyncDependenciesOfMicroservice.kt
> +            }
Validei a implementação com o código antigo e realmente a detecção é realizada corretamente e os testes passam sem problemas. Mantive o novo cenário de testes.

2024-09-29 11:24 UTC, marcelo-vidu commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservices.kt
> +    }
Refatorei a classe com a sugestão do método.

2024-09-29 13:13 UTC, marcelo-vidu commented on app-analyses/src/main/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservices.kt
> +    private val msCoincidences: MutableMap<Visitable, MutableList<Pair<Relationship, String>>> = mutableMapOf()
Fiz um ajuste na exibição que apresenta a deteção com a lista de nomes dos serviços, os tipos detectados e abaixo os membros com os dados completos, assim fica simples de entender o motivo daquela coincidência ter sido detectada.
Veja se faz sentido por favor.

2024-09-29 13:15 UTC, marcelo-vidu commented on app-analyses/src/test/kotlin/com/usvision/analyses/analyzer/CoincidenceOfMicroservicesTest.kt
> +        assertTrue { results[cons2]!!.any { it.second == "sync" } }
Fiz um ajuste na exibição que apresenta a deteção com a lista de nomes dos serviços, os tipos detectados e abaixo os membros com os dados completos, assim fica simples de entender o motivo daquela coincidência ter sido detectada.
Veja se faz sentido por favor.

Sobre os demais serviços que está coincidindo, ele vai apresentar como uma nova instância, assim como fazemos no cyclicdependency por exemplo.

Se A --> B e B --> C tem coincidências, ele vai apresentar duas instâncias da detecção com os nomes dos microsserviços envolvidos e os tipos de coincidências detectadas.

2024-10-06 16:44 UTC, jooaodanieel approved these changes

2024-10-06 20:26 UTC, merged